### ISSUE TITLE
Building with rabbitmq-c git fails

### ISSUE THREAD

**Issue by Tristramg** [alanxz/SimpleAmqpClient#59]
using alanxz/rabbitmq-c@4eaf771fa5f7807c38276b26aaa410bfd136d382 and alanxz/SimpleAmqpClient@44b8b4e14424999c1b5b11829491e0ee42a37494 (currently the latest available) SimpleAmqpClient fails compiling.

It builds correctly with the release 2.2 (as the bug was introduced in 44b8b4e).

The problem is in creating a SSL Channel : 

> /home/tristram/SimpleAmqpClient/src/Channel.cpp: In constructor ‘AmqpClient::Channel::Channel(const string&, int, const string&, const string&, const string&, int, const string&, const string&, const string&)’:
> /home/tristram/SimpleAmqpClient/src/Channel.cpp:134:49: error: too few arguments to function ‘amqp_socket_t\* > amqp_ssl_socket_new(amqp_connection_state_t)’
>      amqp_socket_t\* socket = amqp_ssl_socket_new();

https://github.com/alanxz/SimpleAmqpClient/blob/master/src/Channel.cpp#L134

https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp_openssl.c#L358
