### ISSUE TITLE
SSL disabled build on MS VC++ 12.0 failed due to overloaded method on Channel()

### ISSUE THREAD

**Issue by jg2912** [alanxz/SimpleAmqpClient#110]
Hi Alan,

I tried to build the latest make using rabbitmqc without ssl. it seems complaining about overloaded member function for Channel is not there. I checked your latest fix on SSL option, it is supposed to use below ctor when SSL is not presented. do you know i need to do any tweaks? Thanks!

Channel::Channel(const std::string &,
                 int ,
                 const std::string &,
                 const std::string &,
                 const std::string &,
                 int ,
                 const std::string &,
                 const std::string &,
                 const std::string &)
{
    throw std::logic_error("SSL support has not been compiled into SimpleAmqpClient");
}

error C2511: 'AmqpClient::Channel::Channel(const std::string &,int,const std::string &,const std::string &,const std::string &,int,const std::string &,const std::string &,const std::string &)' : overloaded member function not found in 'AmqpClient::Channel'	

best,
Jiong

**Comment by jg2912** [comment]
for now i am changing ctor definition as below to circumsvent it
....
#else
Channel::Channel(const std::string &host,
	int port,
	const std::string &username,
	const std::string &password,
	const std::string &vhost,
	int frame_max,
	const SSLConnectionParams &ssl_params)
	: m_impl(new Detail::ChannelImpl)
{
    throw std::logic_error("SSL support has not been compiled into SimpleAmqpClient");
}
#endif

**Comment by jg2912** [comment]
...but would like to know did i mess up with something in the original release
